# Generated by Django 5.2.1 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='YouTube', max_length=50)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('channel_id', models.CharField(max_length=255)),
                ('video_id', models.CharField(blank=True, max_length=100)),
                ('live_views', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('avg_watch_seconds', models.IntegerField(default=0)),
                ('subs_gained', models.IntegerField(default=0)),
                ('subs_lost', models.IntegerField(default=0)),
                ('net_subs', models.IntegerField(default=0)),
                ('total_subs', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'channel_id', 'video_id')},
            },
        ),
    ]
