# Generated by Django 5.2.1 on 2025-05-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeanalytics',
            name='ctr',
        ),
        migrations.RemoveField(
            model_name='youtubeanalytics',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='youtubeanalytics',
            name='live_views',
        ),
    ]
